version: '3.8'

services:
  app:
    container_name: SoundBase-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces:cached

    command: sleep infinity
    network_mode: service:db

  db:
    image: mysql:8.4
    container_name: SoundBase-db
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: saoundbase
      MYSQL_PASSWORD: root

volumes:
  mysql-data:
